<?php
session_start();
?>
<!doctype html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <title>BoostYourAccount | Договор публичной оферты</title>
    <meta name="description" content="Договор на предоставление услуг сервисом 'BoostYourAccount'. Используя сервис BoostYourAccount, Вы автоматически соглашаетесь с условиями договора оферты!" />
    <meta name="keywords" content="BoostYourAccount Договор на предоставление услуг" />
    <meta name="author" content="Sahib Zulfigar" />


    <!-- Facebook and Twitter integration -->
    <meta property="og:title" content="BoostYourAccount | Договор публичной оферты" />
    <meta property="og:image" content="https://ru.boostyouraccount.com/img/preview.jpg?v" />
    <meta property="og:url" content="https://ru.boostyouraccount.com/terms-conditions.php" />
    <meta property="og:site_name" content="Boost Your Account" />
    <meta property="og:description" content="Договор на предоставление услуг сервисом 'BoostYourAccount'. Используя сервис BoostYourAccount, Вы автоматически соглашаетесь с условиями договора оферты!" />
    <meta name="twitter:title" content="BoostYourAccount | Договор публичной оферты" />
    <meta name="twitter:image" content="https://ru.boostyouraccount.com/img/preview.jpg?v" />
    <meta name="twitter:url" content="https://ru.boostyouraccount.com/terms-conditions.php" />
    <meta name="twitter:card" content="summary_large_image" />

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <link rel="shortcut icon" href="https://ru.boostyouraccount.com/icon.ico">
    <link rel="apple-touch-icon" href="https://ru.boostyouraccount.com/icon.ico">
    <link rel="canonical" href="https://ru.boostyouraccount.com/terms-conditions.php">


    <link rel="stylesheet" href="css/style.css">
    <script defer src="js/utils.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;900&display=swap" rel="stylesheet">
</head>

<body>
    <?php include "header.php"; ?>
    <section class="center-text-container">
        <p>Privacy Policy</p>
    </section>
    <div class="policy-page">
        <p>This is the Privacy Policy of BOOSTYOURACCOUNT (hereinafter referred to as “Administration”, “we,” “us” or “our”).
            At <a style="color:white" href='https://boostyouraccount.com'>https://boostyouraccount.com</a>, we respect the privacy of our users and are committed to protecting
            their personal information. Our Privacy Policy explains how we collect, use,
            share and protect information in relation to our Website. We collect this information when you visit our website with your
            computer, tablet or mobile phone, as well as during the use of any of the our Websites, services, products
            or services and during the execution by BOOSTYOURACCOUNT of any agreements and agreements with the User.
        </p>
        <p>
            By using the Service, you understand, agree and give your unconditional consent to the collection and
            use of information in accordance with this Privacy Policy. Our Privacy Policy applies to all visitors, users,
            and others who access the Service (“Users”). In case of disagreement with our Privacy Policy, the User
            should refrain from using the Website.
        </p>
        <h1>Definitions</h1>
        <p>
            Data Controller — the natural or legal person who (either alone or jointly or in common with other
            persons) determines the purposes for which and the manner in which any personal information
            are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of
            your Personal Data.
        </p>
        <p>
            Administration — the entire administrative and technical team of the Service «BOOSTYOURACCOUNT»,
            responsible for its development and maintenance of efficiency. The Administration is in direct
            contact with the User and undertakes to provide consulting information on issues directly related
            to the use of the Service.
        </p>
        <p>
            Personal Data — Personal Data means data about a living individual who can be identified from
            those data (or from those and other information either in our possession or likely to come into our
            possession)
        </p>
        <p>
            Usage Data — data collected automatically either generated by the use of the Service or from the
            Service infrastructure itself (for example, the duration of a page visit).ƒ
        </p>
        <p>
            Processing of Personal Data — any operation (action) or a set of those that the Operator
            produces with personal data. They can collect, record, systematize, accumulate, store, clarify (if
            necessary to update or change), extract, use, transfer (distribution, granting, access access),
            depersonalize, block, remove, and even destroy. These operations (actions) can be performed
            both automatically and/or manually.
        </p>
        <p>
            Confidentiality of Personal Data — is a mandatory requirement for the Data Controller or any
            other official working with the User's data to keep the information confidential, without disclosing it
            to outsiders, if the user who provided the personal data has not expressed his consent, and there
            is no legal basis for disclosure.
        </p>
        <p>
            Website — service "BOOSTYOURACCOUNT" that provides services for online promotion in social networks,
            as well as SMM, SEO and PR services on the Internet, located on the Internet at <a style="color:white" href='https://boostyouraccount.com'>https://boostyouraccount.com</a>.
        </p>
        <p>
            User — is any living individual who is using our Website and/or its services and is the subject of
            Personal Data. The User corresponds to the Data Subject, who is the subject of Personal Data.
        </p>
        <p>
            Service — a set of all the Services provided by the Website at <a style="color:white" href='https://boostyouraccount.com'>https://boostyouraccount.com</a> to the User.
        </p>
        <p>
            Services — a set of functions of a technical nature, provided to the User as part of the paid
            purchase of promotion services and advertising. In particular, the Service solves the problem of
            attracting subscribers, likes, reposts, comments, etc., to the User accounts in social networks.
        </p>
        <p>
            Cookies — a short piece of data sent by a web browser or web client to a web server in an HTTP
            request, whenever the User tries to open a page of the site. The fragment is stored on the User's
            computer. "IP address" is a unique network address of a node in a computer network built on
            TCP/IP Protocol.
        </p>
        <h1>General Provisions</h1>
        <p>
            Administration has the right to make changes to this Policy. When changes are made, the Policy
            header indicates the date when the revision was last updated. The new version of the Policy shall
            enter into force upon its posting on the Website at <a style="color:white" href='https://boostyouraccount.com/privacy-policy.php'>https://boostyouraccount.com/privacy-policy.php</a>,
            unless otherwise provided by the new version of the Policy.
        </p>
        <h1>User’s Personal Information that is processed by Data Controller</h1>
        <p>
            The Website does not verify the accuracy of the personal information provided by the User and is
            not able to assess their legal capacity.
        </p>
        <p>
            This Policy applies only to information processed in the course of using the Website.
            Administration does not control and is not responsible for the processing of information by thirdparty websites to which the User can click on the links available on the Website.
        </p>
        <p>
            "Personal information" in this Policy refers to:
        </p>
        <ul>
            <li>information provided by the User independently during checkout (order payment) or
                during the use of the Website, including personal data of the User. The information
                required for the Website is marked in a special way. Other information is provided by the
                User at their discretion;
            </li>
            <li>
                data that is automatically transmitted to the Website in the course of the User's use of the
                Website using the software installed on the User's device, including IP address, Cookie
                data, information about The user's browser (or other program by which the website is
                accessed), technical specifications of the equipment and software used by the User, date
                and time of access To the website, addresses of the requested pages and other similar
                information;
            </li>
            <li>
                other User information (including Usage Data), the processing of which is provided by the
                terms of use of the Website.
            </li>
        </ul>
        <h1>Means and Purposes for Processing User’s Personal Data</h1>
        <p>
            Data Controller collects and stores only the personal information that is necessary for the
            provision of services or the execution of agreements and contracts with the User, except in cases
            where the legislation provides for the mandatory storage of personal information for a period
            specified by law.
        </p>
        <p>
            Data Controller processes the User's personal information for the following purposes:
        </p>
        <ul>
            <li>
                identification of the parties to the services agreements and contracts with the Website;
            </li>
            <li>
                provision of personalized services to the User, as well as execution of agreements and
                contracts;
            </li>
            <li>
                sending notifications, requests and information regarding the use of the Website,
                execution of agreements and contracts, as well as processing requests and applications
                from the User;
            </li>
            <li>
                improving the quality of Website usability for the User, development of new services;
            </li>
            <li>
                targeting of advertising materials;
            </li>
            <li>
                conducting statistical and other research based on depersonalized data.
            </li>
        </ul>
        <h1>Terms of processing User's Personal information and its transfer to third partiesƒ</h1>
        <p>
            With respect to the User's personal information, its confidentiality is maintained, except in cases
            of voluntary provision by the User of information about himself for general access to an unlimited
            number of persons.
        </p>
        <p>
            Administration has the right to transfer the User's personal information to third parties in the
            following cases:
        </p>
        <ul>
            <li>
                The User agreed to such actions;ƒ
            </li>
            <li>
                The transfer is necessary for the User to use a certain service or for the execution of a
                certain agreement or contract with the User;
            </li>
            <li>
                The transfer is necessary for the functioning and efficiency of the Website;
            </li>
            <li>
                The transfer is provided for by applicable law within the procedure
                established by the legislation;
            </li>
            <li>
                Such transfer takes place within the framework of sale or other transfer of business (in
                whole or in part), while the purchaser assumes all obligations to comply with the terms of
                this Policy in relation to the personal information received by them;
            </li>
            <li>
                In order to protect the rights and legitimate interests of the Website or third parties in
                cases where the User violates the Website’s User Agreement, this Privacy Policy, or
                documents containing the terms of use of specific services.
            </li>
            <li>
                As a result of the processing of the User's personal information by depersonalizing it,
                depersonalized statistical data are obtained, which are transmitted to a third party for
                research, work or services on behalf of the Website.
            </li>
        </ul>
        <h1>Change and Deletion of Personal Information. Mandatory Data Storage</h1>
        <p>
            User may at any time change (update, supplement) the personal information provided by them by
            contacting the Administration at the address support@boostyouraccount.com.
        </p>
        <p>
            Rights under paragraph 6.1. of the Privacy Policy may be restricted as required by law. For
            example, such restrictions may require the Administration to retain the information changed or
            deleted by the User for a period established by law and to transmit such information in
            accordance with the procedure established by law to the public authority.
        </p>
        <h1>Protection of User's Personal Information</h1>
        <p>
            Administration shall take the necessary and sufficient organizational and technical measures to
            protect User's personal information from unauthorized or accidental access, destruction,
            modification, blocking, copying, distribution, as well as other illegal actions with it by third parties.
        </p>
        <h1>Changes to the Privacy Policy</h1>
        <p>
            Administration has the right to make changes to this privacy Policy. When making changes in the
            current version, the date of the last update is indicated. The new version of the Policy shall enter
            into force upon its posting, unless otherwise provided by the new version of the Policy. The
            current version is always available on the website under privacy policy.
        </p>


    </div>
    <?php include "footer.html"; ?>
</body>

</html>